name: test
channels:
  - conda-forge
dependencies:
    # Base depends
  - python ==3.11
  - numpy >=1.23
  - nomkl

    # Backends
  - tensorflow-cpu
  - dask
  - sparse
  - pytorch-cpu
  - jax

    # Testing
  - autoflake
  - black
  - codecov
  - isort
  - mypy
  - pytest
  - pytest-cov
