name: test
channels:
  - conda-forge
dependencies:
    # Base depends
  - python
  - numpy
  - nomkl

    # Backends
  - tensorflow ==1.14.*
  - dask ==1.1.*

    # Testing
  - pytest
  - codecov
  - pytest-cov
