name: test
channels:
  - pytorch
  - conda-forge
dependencies:
    # Base depends
  - python >=3.9
  - pytorch::pytorch >=2.0,<3.0.0a
  - pytorch::cpuonly

    # Testing
  - autoflake
  - black 
  - codecov
  - isort
  - mypy
  - pytest
  - pytest-cov
